[project]
authors = [{name = "KhalilM94", email = "khalil.misbah@protonmail.com"}]
license = "MIT"
name = "yg-eo-soilnet"
requires-python = ">= 3.10"
version = "0.1.0"
readme = "README.md"
dependencies = ["mlflow==3.14.*", "psutil>=7.2.2,<8", "pip>=26.1.2,<27"]

[project.urls]
Homepage = "https://github.com/KhalilM94/yg-eo-soilnet"
Repository = "https://github.com/KhalilM94/yg-eo-soilnet.git" 

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.hatch.build.targets.wheel]
packages = ["src/yg_eo_soilnet"]

[tool.pixi.workspace]
channels = ["conda-forge", "main", "r", "msys2", "nvidia"]
name = "yg_eo_soilnet"
platforms = ["linux-64", "win-64", "osx-arm64", "osx-64"]
version = "0.1.0"

[tool.pixi.pypi-dependencies]
yg_eo_soilnet = { path = ".", editable = true }

[tool.pixi.tasks]
mlflow = { cmd = "mlflow ui", env = { MLFLOW_ALLOW_FILE_STORE = "true" } }

[tool.pixi.feature.prod-core.dependencies]
python = ">=3.11,<3.13"
scikit-learn = ">=1.9.0,<2"
shap = ">=0.50.0,<0.53"
pyproj = ">=3.7.2,<4"
numpy = ">=2.4.6,<3"
geopandas = ">=1.1.4,<2"
matplotlib = ">=3.11.0,<4"
scipy = ">=1.18.0,<2"
pandas = "<3"
pytorch = ">=2.12.1,<3"
seaborn = ">=0.13.2,<0.14"

[tool.pixi.feature.gpu-backend.system-requirements]
cuda = "12.0"

[tool.pixi.feature.gpu-backend.target.linux-64.pypi-dependencies]
xgboost = ">=3.3.0, <4"

[tool.pixi.feature.gpu-backend.target.win-64.pypi-dependencies]
xgboost = ">=3.3.0, <4"

[tool.pixi.environments]
core = { features = ["prod-core", "cpu-backend"], solve-group = "default" }
core-gpu = { features = ["prod-core", "gpu-backend"], solve-group = "default" }
dev = { features = ["prod-core", "gpu-backend", "dev"], solve-group = "core-gpu" }
explore = { features = ["prod-core", "cpu-backend", "explore"], solve-group = "core" }

[tool.pixi.feature.dev.tasks]
dev-env = "pixi shell -e dev"
test = "pytest ./tests"
lint = "ruff lint"

[tool.pixi.feature.explore.tasks]
notebook = "jupyter lab"

[tool.pixi.feature.cpu-backend.dependencies]
py-xgboost = ">=3.3.0,<4"

[dependency-groups]
explore = ["jupyterlab"]
test = ["pytest", "ruff", "pytest-cov"]
docs = ["sphinx"]
dev = [{include-group = "test"}, {include-group = "docs"}]

