DATA_FOLDER: "/home/kmisbah/CESBIO/AL_Moutmir/Soil_Datasets/soil_dataset_20251118_140815"
DATA_FILE: "Morocco_soil_analysis_filtered_covariates_2026.csv"
SOIL_GROUPS_FILE_PATH: "../soil_groups.txt"
BANDS_CSV_PATH: "../bandsList.csv"
WORLDCLIM_CSV_PATH: "../worldclim.csv"
TEST_SIZE: 0.2

CLUSTERING_STRATEGY:
  enabled: False
  class_path: helpers.model_config_factory.KMeansClusterStrategy #SpatialGridClusterStrategy / KMeansClusterStrategy
  params:
    n_clusters: 12
    # cell_size_m: 5000

SPLIT_STRATEGY: "kfold" # "groupkfold" or "kfold"
ENABLE_SPATIAL_HOLDOUT_WHEN_GROUPKFOLD: True
SPATIAL_HOLDOUT_CELL_SIZE_M: 5000

RANDOM_SEED: 42
MIN_FEATURE_COUNT: 10
MAX_FEATURE_DROP_RATIO_WARNING: 0.9

TREE_CATEGORICAL_ENCODING: "onehot" # onehot | ordinal | auto
TREE_ONEHOT_MAX_CATEGORIES: 30

FAIL_IF_ALL_MODELS_FAIL_FOR_TARGET: True
FAIL_ON_MODEL_ERROR: False

IGNORE_BANDS: False  # or false to skip ignoring
N_BANDS: 234        # optional: number of bands, default to 234 in code if missing

COLUMNS_TO_TRANSFORM: []

TARGET_COLUMNS:
  - sand_pct
  - clay_pct
  - total_silt_pct
  # - fine_silt_pct
  # - coarse_silt_pct
  # - coarse_element_pct
  # - ph_water
  # - caco3_pct_total
  # - caco3_active_pct
  # - c_e_c_meq_100g
  # - ce_ext1_5_ms_cm
  # - na2o_ppm
  # - cl_ppm
  # - na_meq_100g
  # - c_n_ratio
  # - organic_matter_pct
  - organic_matter_g_kg
  - exchangeable_k2o_ppm
  - p2o5_ehangable_olsen_ppm
  # - mgo_ppm
  # - cao_ppm
  # - iron_ppm_dtpa
  # - mn_ppm_dtpa
  # - cu_ppm_dtpa
  # - zn_ppm_dtpa
  # - b_ppm_hot_water
CATEGORICAL_FEATURES:
  - SU_WRB1_PH

EXCLUDE_CATEGORICAL:
  #- UNWANTED_CAT_COL

ELIMINATED_FEATURES:
  - geometry
  - uuid
  - cluster
  # - lat
  # - lon
  - date
  - sand_pct
  - clay_pct
  - total_silt_pct
  - fine_silt_pct
  - coarse_silt_pct
  - coarse_element_pct
  - ph_water
  - caco3_pct_total
  - caco3_active_pct
  - c_e_c_meq_100g
  - ce_ext1_5_ms_cm
  - na2o_ppm
  - cl_ppm
  - na_meq_100g
  - c_n_ratio
  - organic_matter_pct
  - organic_matter_g_kg
  - exchangeable_k2o_ppm
  - p2o5_ehangable_olsen_ppm
  - mgo_ppm
  - cao_ppm
  - iron_ppm_dtpa
  - mn_ppm_dtpa
  - cu_ppm_dtpa
  - zn_ppm_dtpa
  - b_ppm_hot_water
  
  # - SU_WRB1_PH

  - depth_from_cm
  - depth_to_cm
  - Elevation
  - GPP
  - ET
  - LST
  - NDVI
  - Slope
  - Aridity_Index
  - TWI
  - bio01
  - bio02
  - bio03
  - bio04
  - bio05
  - bio06
  - bio07
  - bio08
  - bio09
  - bio10
  - bio11
  - bio12
  - bio13
  - bio14
  - bio15
  - bio16
  - bio17
  - bio18
  - bio19
  
  - S2_B2
  - S2_B3
  - S2_B4
  - S2_B8
  - S2_B11
  - S2_B12
  - S2_B2_median
  - S2_B3_median
  - S2_B4_median
  - S2_B8_median


  - S2_B5_median
  - S2_B6_median
  - S2_B7_median
  - S2_B8A_median
  - S2_B11_median
  - S2_B12_median

  - S2_B2_min
  - S2_B3_min
  - S2_B4_min
  - S2_B5_min
  - S2_B6_min
  - S2_B7_min
  - S2_B8_min
  - S2_B8A_min
  - S2_B11_min
  - S2_B12_min

  - S2_B2_max
  - S2_B3_max
  - S2_B4_max
  - S2_B5_max
  - S2_B6_max
  - S2_B7_max
  - S2_B8_max
  - S2_B8A_max
  - S2_B11_max
  - S2_B12_max

  - L1
  - DPL1
  - A1
  - W1
  - D1
  - L2
  - DPL2
  - A2
  - W2
  - D2
  - A1+A2
  - K1
  - K2
  - K3
  - K4
  - K5
  
  - S2_B11
  - S2_B12
  - S2_B2
  - S2_B3
  - S2_B4
  - S2_B5
  - S2_B6
  - S2_B7
  - S2_B8
  - S2_B8A

  - ET_DJF_long
  - ET_DJF_mid
  - ET_DJF_short
  - ET_DJF_trend
  - ET_JJA_long
  - ET_JJA_mid
  - ET_JJA_short
  - ET_JJA_trend
  - ET_MAM_long
  - ET_MAM_mid
  - ET_MAM_short
  - ET_MAM_trend
  - ET_SON_long
  - ET_SON_mid
  - ET_SON_short
  - ET_SON_trend
  - Elevation
  - Gpp_DJF_long
  - Gpp_DJF_mid
  - Gpp_DJF_short
  - Gpp_DJF_trend
  - Gpp_JJA_long
  - Gpp_JJA_mid
  - Gpp_JJA_short
  - Gpp_JJA_trend
  - Gpp_MAM_long
  - Gpp_MAM_mid
  - Gpp_MAM_short
  - Gpp_MAM_trend
  - Gpp_SON_long
  - Gpp_SON_mid
  - Gpp_SON_short
  - Gpp_SON_trend
  - LST_Day_1km_DJF_long
  - LST_Day_1km_DJF_mid
  - LST_Day_1km_DJF_short
  - LST_Day_1km_DJF_trend
  - LST_Day_1km_JJA_long
  - LST_Day_1km_JJA_mid
  - LST_Day_1km_JJA_short
  - LST_Day_1km_JJA_trend
  - LST_Day_1km_MAM_long
  - LST_Day_1km_MAM_mid
  - LST_Day_1km_MAM_short
  - LST_Day_1km_MAM_trend
  - LST_Day_1km_SON_long
  - LST_Day_1km_SON_mid
  - LST_Day_1km_SON_short
  - LST_Day_1km_SON_trend
  - NDVI_DJF_long
  - NDVI_DJF_mid
  - NDVI_DJF_short
  - NDVI_DJF_trend
  - NDVI_JJA_long
  - NDVI_JJA_mid
  - NDVI_JJA_short
  - NDVI_JJA_trend
  - NDVI_MAM_long
  - NDVI_MAM_mid
  - NDVI_MAM_short
  - NDVI_MAM_trend
  - NDVI_SON_long
  - NDVI_SON_mid
  - NDVI_SON_short
  - NDVI_SON_trend
  
  # - B11_q10
  # - B11_q20
  # - B11_q30
  # - B11_q40
  # - B11_q50
  # - B11_q60
  # - B11_q70
  # - B11_q80
  # - B11_q90
  # - B12_q10
  # - B12_q20
  # - B12_q30
  # - B12_q40
  # - B12_q50
  # - B12_q60
  # - B12_q70
  # - B12_q80
  # - B12_q90
  # - B2_q10
  # - B2_q20
  # - B2_q30
  # - B2_q40
  # - B2_q50
  # - B2_q60
  # - B2_q70
  # - B2_q80
  # - B2_q90
  # - B3_q10
  # - B3_q20
  # - B3_q30
  # - B3_q40
  # - B3_q50
  # - B3_q60
  # - B3_q70
  # - B3_q80
  # - B3_q90
  # - B4_q10
  # - B4_q20
  # - B4_q30
  # - B4_q40
  # - B4_q50
  # - B4_q60
  # - B4_q70
  # - B4_q80
  # - B4_q90
  # - B5_q10
  # - B5_q20
  # - B5_q30
  # - B5_q40
  # - B5_q50
  # - B5_q60
  # - B5_q70
  # - B5_q80
  # - B5_q90
  # - B6_q10
  # - B6_q20
  # - B6_q30
  # - B6_q40
  # - B6_q50
  # - B6_q60
  # - B6_q70
  # - B6_q80
  # - B6_q90
  # - B7_q10
  # - B7_q20
  # - B7_q30
  # - B7_q40
  # - B7_q50
  # - B7_q60
  # - B7_q70
  # - B7_q80
  # - B7_q90
  # - B8_q10
  # - B8_q20
  # - B8_q30
  # - B8_q40
  # - B8_q50
  # - B8_q60
  # - B8_q70
  # - B8_q80
  # - B8_q90
  # - B8A_q10
  # - B8A_q20
  # - B8A_q30
  # - B8A_q40
  # - B8A_q50
  # - B8A_q60
  # - B8A_q70
  # - B8A_q80
  # - B8A_q90