PLSRegression:
  enabled: False
  modeltype: "ml"
  import_path: sklearn.cross_decomposition.PLSRegression
  params:
    model__n_components: [2, 4, 6, 8, 10, 12, 14, 16, 18]

Ridge:
  enabled: False
  modeltype: "ml"
  import_path: sklearn.linear_model.Ridge
  params:
    model__alpha: [0.01, 0.1, 1, 10, 100, 1000]

GradientBoosting:
  enabled: False
  modeltype: "ml"
  import_path: sklearn.ensemble.GradientBoostingRegressor
  init_args:
    random_state: 42
  params:
    model__n_estimators: [50, 100]
    model__max_depth: [5]
    model__learning_rate: [0.1]
    
    # model__n_estimators: [50, 150, 250]
    # model__learning_rate: [0.01, 0.1, 0.2]
    # model__max_depth: [5, 13, 21]

XGBoost:
  enabled: True
  modeltype: "ml"
  import_path: xgboost.XGBRegressor
  init_args:
    random_state: 123
    objective: "reg:quantileerror" #"reg:squarederror" 
    quantile_alpha: [0.5]
    tree_method: "hist" 
    #device: "cuda"
  params:
    model__n_estimators: [500]
    model__max_depth: [3, 4, 5, 6, 7, 8, 9, 10]
    model__learning_rate: [0.01, 0.005]
    model__subsample: [0.8]
    model__reg_alpha: [0, 0.1, 1]
    model__reg_lambda: [1, 10, 100]
    # model__colsample_bytree: [0.8, 1.0]
    # model__min_child_weight: [1, 5]